# -*- coding: utf-8 -*-
"""
Created on Wed May 14 09:39:50 2025

@author: p226646
"""

dados={
       "JUVENAL":   {"CELULAR":"991234567","EMAIL":"juvenal@gmailx.com","ALTURA":1.70,"PESO":80},
       "PERCIVAL":  {"CELULAR":"994567897","EMAIL":"percival@gmailx.com","ALTURA":1.65,"PESO":90},
       "ADAMASTOR": {"CELULAR":"991223231","EMAIL":"adamastor@gmailx.com","ALTURA":1.72,"PESO":88},
       "JUVENTINA": {"CELULAR":"993422312","EMAIL":"juventina@gmailx.com","ALTURA":1.80,"PESO":72},
       "OMOPLATA":  {"CELULAR":"923234554","EMAIL":"omoplata@gmailx.com","ALTURA":1.55,"PESO":65},
       }

#IMPLEMENTAR AS SEGUINTES
#ROTINAS ESTATISTICAS:
#   QUEM TEM A MAIOR ALTURA
#   QUEM TEM A MENOR ALTURA
#   QUEM TEM A MAIOR PESO
#   QUEM TEM A MENOR PESO
#   PESO MEDIO
#   ALTURA MEDIA
#   O NOME COM MAIOR NUMERO DE LETRAS
#   O NOME COM MENOR NUMERO DE LETRAS
#   CALCULAR O IMC
#   QUEM TEM A MAIOR IMC
#   QUEM TEM A MENOR IMC